# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Cuisine.create!(name: "Afrikanisches")
Cuisine.create!(name: "Amerikanisches")
Cuisine.create!(name: "Asiatisches")
Cuisine.create!(name: "Australisches")
Cuisine.create!(name: "Bengalesisches")
Cuisine.create!(name: "Biergarten")
Cuisine.create!(name: "Bio")
Cuisine.create!(name: "Boots")
Cuisine.create!(name: "Brauhaus")
Cuisine.create!(name: "Crêperie")
Cuisine.create!(name: "Erlebnis")
Cuisine.create!(name: "Europäisches")
Cuisine.create!(name: "Familien-")
Cuisine.create!(name: "Fisch-")
Cuisine.create!(name: "Fondue-")
Cuisine.create!(name: "Französisches")
Cuisine.create!(name: "Fusion-")
Cuisine.create!(name: "Gourmet")
Cuisine.create!(name: "Griechisches")
Cuisine.create!(name: "Indisches")
Cuisine.create!(name: "Kanadisches")
Cuisine.create!(name: "Kantine")
Cuisine.create!(name: "Karibisches")
Cuisine.create!(name: "Koscheres")
Cuisine.create!(name: "Kreolisches")
Cuisine.create!(name: "Kroatisches")
Cuisine.create!(name: "Kubanisches")
Cuisine.create!(name: "Lateinamerikanisches")
Cuisine.create!(name: "Marokkanisches")
Cuisine.create!(name: "Mediterranes")
Cuisine.create!(name: "Mexikanisches")
Cuisine.create!(name: "Orientalisches")
Cuisine.create!(name: "Osteuropäisches")
Cuisine.create!(name: "Pakistanisches")
Cuisine.create!(name: "Polnisches")
Cuisine.create!(name: "Portugiesisches")
Cuisine.create!(name: "Russisches")
Cuisine.create!(name: "Schwedisches")
Cuisine.create!(name: "Schweizer")
Cuisine.create!(name: "Spanisches")
Cuisine.create!(name: "Steak-")
Cuisine.create!(name: "Strand")
Cuisine.create!(name: "Sudanesisches")
Cuisine.create!(name: "Sushi")
Cuisine.create!(name: "Tapas")
Cuisine.create!(name: "TexMex-")
Cuisine.create!(name: "Thai")
Cuisine.create!(name: "Tschechisches")
Cuisine.create!(name: "Tunesisches")
Cuisine.create!(name: "Türkisches")
Cuisine.create!(name: "Ungarisches")
Cuisine.create!(name: "Veganes")
Cuisine.create!(name: "Vegetarisches")
Cuisine.create!(name: "Weinbar")
Cuisine.create!(name: "XXL-")
Cuisine.create!(name: "Äthiopisches")
Cuisine.create!(name: "Österreichisches")

